-- Creacion de tablas
CREATE TABLE DEPARTAMENTO (NUMDEPTO INT PRIMARY KEY AUTO_INCREMENT, NOMDEPTO VARCHAR(100), UBICACIONDPTO VARCHAR(100));
CREATE TABLE EMPLEADO (NUMEMPLEADO INT PRIMARY KEY AUTO_INCREMENT, NOMBRE VARCHAR(100), NUMDEPTO INT);
CREATE TABLE USUARIOS_ADMIN (ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT, CORREO VARCHAR(100), PASS VARCHAR(100));
ALTER TABLE EMPLEADO
ADD CONSTRAINT DEP_EMPLEADO
FOREIGN KEY (NUMDEPTO)
REFERENCES DEPARTAMENTO (NUMDEPTO);
-- ALTER TABLE USUARIOS_ADMIN ADD (PRIMER_NOMBRE VARCHAR(100), SEGUNDO_NOMBRE VARCHAR(100));
-- ALTER TABLE USUARIOS_ADMIN ADD (NOMBRE VARCHAR(100));
-- Creacion de secuencias para los Id Autoincrementables

-- Insert poblar tablas
INSERT INTO USUARIOS_ADMIN VALUES(0, 'admin@correo.cl','123');

INSERT INTO DEPARTAMENTO VALUES(0 ,'INFORMATICA','CHILE');
INSERT INTO DEPARTAMENTO VALUES(0,'REDES','CHILE');
INSERT INTO DEPARTAMENTO VALUES(0,'PARTES','CHILE');
INSERT INTO DEPARTAMENTO VALUES(0,'SALUD','CHILE');
INSERT INTO DEPARTAMENTO VALUES(0,'BIENESTAR','CHILE');
INSERT INTO DEPARTAMENTO VALUES(0,'ASEO Y ORNATO','CHILE');
INSERT INTO DEPARTAMENTO VALUES(0,'CONTABILIDAD','PERU');
INSERT INTO DEPARTAMENTO VALUES(0,'RRHH','COLOMBIA');
INSERT INTO DEPARTAMENTO VALUES(0,'ASEO Y ORNATO','ARGENTINA');
INSERT INTO DEPARTAMENTO VALUES(0,'CONTABILIDAD','BOLIVIA');
INSERT INTO DEPARTAMENTO VALUES(0,'RRHH','MEXICO');
INSERT INTO DEPARTAMENTO VALUES(0,'CARRETE','CHILE');
INSERT INTO DEPARTAMENTO VALUES(0,'SEGURIDAD','PERU');
INSERT INTO DEPARTAMENTO VALUES(0,'MARKETING','COLOMBIA');
INSERT INTO DEPARTAMENTO VALUES(0,'MECANICA','CHILE');

INSERT INTO EMPlEADO VALUES (0,'Matias Zarate', 15);
INSERT INTO EMPlEADO VALUES (0,'Felipe Perez', 15);
INSERT INTO EMPlEADO VALUES (0,'Bob Marley', 15);
INSERT INTO EMPlEADO VALUES (0,'Pedro Polanco', 15);
INSERT INTO EMPlEADO VALUES (0,'Eduardo Azul', 15);
INSERT INTO EMPlEADO VALUES (0,'Oscar Fernandez', 14);
INSERT INTO EMPlEADO VALUES (0,'Maria Jose Velasquez', 14);
INSERT INTO EMPlEADO VALUES (0,'Fernanda Parra', 14);
INSERT INTO EMPlEADO VALUES (0,'Teresa Valdez', 14);
INSERT INTO EMPlEADO VALUES (0,'Ignacio MacGreg', 14);
INSERT INTO EMPlEADO VALUES (0,'Rodrigo Zarabia', 13);
INSERT INTO EMPlEADO VALUES (0,'Marcelo Zapata', 13);
INSERT INTO EMPlEADO VALUES (0,'Mark Jeres', 13);
INSERT INTO EMPlEADO VALUES (0,'Cristian Aguirre', 13);
INSERT INTO EMPlEADO VALUES (0,'Julian Martel', 13);
INSERT INTO EMPlEADO VALUES (0,'Kilos Demetrio', 12);
INSERT INTO EMPlEADO VALUES (0,'Astorga Daniel', 12);
INSERT INTO EMPlEADO VALUES (0,'Yeny Marlen', 12);
INSERT INTO EMPlEADO VALUES (0,'Julia Zapata', 12);
INSERT INTO EMPlEADO VALUES (0,'Esteban Cerrado', 12);
INSERT INTO EMPlEADO VALUES (0,'Kilos Demetrio Azul', 11);
INSERT INTO EMPlEADO VALUES (0,'Pablo Carmona', 11);
INSERT INTO EMPlEADO VALUES (0,'Ramon Vicencio', 11);
INSERT INTO EMPlEADO VALUES (0,'Julia Veracruz', 11);
INSERT INTO EMPlEADO VALUES (0,'Joaquin Mendez', 11);
INSERT INTO EMPlEADO VALUES (0,'Ricardo Abrilar', 10);
INSERT INTO EMPlEADO VALUES (0,'Rocio Vicencio', 10);
INSERT INTO EMPlEADO VALUES (0,'Bianca Vicencio', 10);
INSERT INTO EMPlEADO VALUES (0,'Graciela LLancavil', 10);
INSERT INTO EMPlEADO VALUES (0,'Enrique Carmona', 10);
INSERT INTO EMPlEADO VALUES (0,'Nora Allen', 9);
INSERT INTO EMPlEADO VALUES (0,'Ramon Cisco', 9);
INSERT INTO EMPlEADO VALUES (0,'Frank Martin', 9);
INSERT INTO EMPlEADO VALUES (0,'Milena Snow', 9);
INSERT INTO EMPlEADO VALUES (0,'Ruth Vitis', 9);
INSERT INTO EMPlEADO VALUES (0,'Sol Marisol', 8);
INSERT INTO EMPlEADO VALUES (0,'Jorge Carmona', 8);
INSERT INTO EMPlEADO VALUES (0,'Miguel Mac', 8);
INSERT INTO EMPlEADO VALUES (0,'Rafael Alarcon', 8);
INSERT INTO EMPlEADO VALUES (0,'Ruth Vitis', 8);
INSERT INTO EMPlEADO VALUES (0,'Jhon Nieve', 7);
INSERT INTO EMPlEADO VALUES (0,'Martin Escoses', 7);
INSERT INTO EMPlEADO VALUES (0,'Alex Citrico', 7);
INSERT INTO EMPlEADO VALUES (0,'Marcelo de Cachureos', 7);
INSERT INTO EMPlEADO VALUES (0,'Alfonso Mastil', 7);
INSERT INTO EMPlEADO VALUES (0,'Juan Quiñones', 6);
INSERT INTO EMPlEADO VALUES (0,'Adamiro Rojas', 6);
INSERT INTO EMPlEADO VALUES (0,'Fernando Maciel', 6);
INSERT INTO EMPlEADO VALUES (0,'Carolina Merlot', 6);
INSERT INTO EMPlEADO VALUES (0,'Casandra Parra', 6);
INSERT INTO EMPlEADO VALUES (0,'Salomon Clavel', 5);
INSERT INTO EMPlEADO VALUES (0,'Quiste Martes', 5);
INSERT INTO EMPlEADO VALUES (0,'Carlos Zaul', 5);
INSERT INTO EMPlEADO VALUES (0,'Eduardo Bomvalet', 5);
INSERT INTO EMPlEADO VALUES (0,'Arturo Prat', 5);
INSERT INTO EMPlEADO VALUES (0,'Maria Jose Pinganilla', 4);
INSERT INTO EMPlEADO VALUES (0,'Carlonia Marsobia', 4);
INSERT INTO EMPlEADO VALUES (0,'Jose Jose', 4);
INSERT INTO EMPlEADO VALUES (0,'Esternon Peres', 4);
INSERT INTO EMPlEADO VALUES (0,'Ivon Cadiz', 4);
INSERT INTO EMPlEADO VALUES (0,'Moscard Trek', 3);
INSERT INTO EMPlEADO VALUES (0,'Hugo Luis Merc', 3);
INSERT INTO EMPlEADO VALUES (0,'Casimiro Lavaca', 3);
INSERT INTO EMPlEADO VALUES (0,'Aston Gonzalez', 3);
INSERT INTO EMPlEADO VALUES (0,'Crecencio Fretere', 3);
INSERT INTO EMPlEADO VALUES (0,'Juan Pedro Pazola', 2);
INSERT INTO EMPlEADO VALUES (0,'Roquefort Martin', 2);
INSERT INTO EMPlEADO VALUES (0,'Carlos Espertes', 2);
INSERT INTO EMPlEADO VALUES (0,'Jino Janos', 2);
INSERT INTO EMPlEADO VALUES (0,'Ether Certero', 2);
INSERT INTO EMPlEADO VALUES (0,'Pepe Grillo', 1);
INSERT INTO EMPlEADO VALUES (0,'Marisol Luna', 1);
INSERT INTO EMPlEADO VALUES (0,'Pedro Cortisona', 1);
INSERT INTO EMPlEADO VALUES (0,'Eugenio Mundial', 1);
INSERT INTO EMPlEADO VALUES (0,'Nelson Gertred', 1);

COMMIT;

SELECT * FROM DEPARTAMENTO;
SELECT * FROM EMPLEADO;

SELECT * FROM USUARIOS_ADMIN WHERE CORREO = 'admin@correo.cl'AND PASS = '123';

SELECT * FROM departamento, empleado;

SELECT MAX(NUMDEPTO)+1 FROM DEPARTAMENTO;

DROP TABLE USUARIOS_ADMIN;
DROP TABLE EMPLEADO;
DROP TABLE DEPARTAMENTO;

DROP SEQUENCE USUARIO_SEC;
DROP SEQUENCE DEPTO_SEC;
DROP SEQUENCE EMPL_SEC;