-- Creacion de tablas
CREATE TABLE DEPARTAMENTO (NUMDEPTO NUMBER PRIMARY KEY NOT NULL, NOMDEPTO VARCHAR(100), UBICACIONDPTO VARCHAR(100));

CREATE TABLE EMPLEADO (NUMEMPLEADO NUMBER PRIMARY KEY, NOMBRE VARCHAR(100), NUMDEPTO INTEGER);

CREATE TABLE USUARIOS_ADMIN (ID_USUARIO NUMBER PRIMARY KEY, CORREO VARCHAR(100), PASS VARCHAR(100));

ALTER TABLE EMPLEADO 
ADD CONSTRAINT DEP_EMPLEADO
FOREIGN KEY (NUMDEPTO)
REFERENCES DEPARTAMENTO (NUMDEPTO) ON DELETE CASCADE;

--ALTER TABLE USUARIOS_ADMIN ADD (PRIMER_NOMBRE VARCHAR(100), SEGUNDO_NOMBRE VARCHAR(100));
--ALTER TABLE USUARIOS_ADMIN ADD (NOMBRE VARCHAR(100));

--Creacion de secuencias para los Id Autoincrementables
CREATE SEQUENCE DEPTO_SEC
 START WITH     1
 INCREMENT BY   1;
 
CREATE SEQUENCE EMPL_SEC
 START WITH     1
 INCREMENT BY   1;

CREATE SEQUENCE USUARIO_SEC
 START WITH     1
 INCREMENT BY   1;
 
-- Insert poblar tablas
INSERT INTO USUARIOS_ADMIN VALUES(USUARIO_SEC.NEXTVAL, 'admin@correo.cl','123');

INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL ,'INFORMATICA','CHILE');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'REDES','CHILE');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'PARTES','CHILE');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'SALUD','CHILE');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'BIENESTAR','CHILE');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'ASEO Y ORNATO','CHILE');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'CONTABILIDAD','PERU');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'RRHH','COLOMBIA');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'ASEO Y ORNATO','ARGENTINA');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'CONTABILIDAD','BOLIVIA');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'RRHH','MEXICO');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'CARRETE','CHILE');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'SEGURIDAD','PERU');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'MARKETING','COLOMBIA');
INSERT INTO DEPARTAMENTO VALUES(DEPTO_SEC.NEXTVAL,'MECANICA','CHILE');

INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Matias Zarate', 15);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Felipe Perez', 15);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Bob Marley', 15);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Pedro Polanco', 15);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Eduardo Azul', 15);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Oscar Fernandez', 14);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Maria Jose Velasquez', 14);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Fernanda Parra', 14);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Teresa Valdez', 14);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Ignacio MacGreg', 14);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Rodrigo Zarabia', 13);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Marcelo Zapata', 13);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Mark Jeres', 13);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Cristian Aguirre', 13);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Julian Martel', 13);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Kilos Demetrio', 12);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Astorga Daniel', 12);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Yeny Marlen', 12);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Julia Zapata', 12);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Esteban Cerrado', 12);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Kilos Demetrio Azul', 11);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Pablo Carmona', 11);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Ramon Vicencio', 11);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Julia Veracruz', 11);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Joaquin Mendez', 11);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Ricardo Abrilar', 10);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Rocio Vicencio', 10);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Bianca Vicencio', 10);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Graciela LLancavil', 10);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Enrique Carmona', 10);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Nora Allen', 9);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Ramon Cisco', 9);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Frank Martin', 9);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Milena Snow', 9);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Ruth Vitis', 9);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Sol Marisol', 8);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Jorge Carmona', 8);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Miguel Mac', 8);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Rafael Alarcon', 8);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Ruth Vitis', 8);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Jhon Nieve', 7);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Martin Escoses', 7);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Alex Citrico', 7);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Marcelo de Cachureos', 7);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Alfonso Mastil', 7);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Juan Quiñones', 6);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Adamiro Rojas', 6);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Fernando Maciel', 6);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Carolina Merlot', 6);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Casandra Parra', 6);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Salomon Clavel', 5);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Quiste Martes', 5);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Carlos Zaul', 5);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Eduardo Bomvalet', 5);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Arturo Prat', 5);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Maria Jose Pinganilla', 4);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Carlonia Marsobia', 4);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Jose Jose', 4);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Esternon Peres', 4);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Ivon Cadiz', 4);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Moscard Trek', 3);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Hugo Luis Merc', 3);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Casimiro Lavaca', 3);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Aston Gonzalez', 3);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Crecencio Fretere', 3);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Juan Pedro Pazola', 2);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Roquefort Martin', 2);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Carlos Espertes', 2);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Jino Janos', 2);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Ether Certero', 2);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Pepe Grillo', 1);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Marisol Luna', 1);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Pedro Cortisona', 1);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Eugenio Mundial', 1);
INSERT INTO EMPlEADO VALUES (EMPL_SEC.NEXTVAL,'Nelson Gertred', 1);

COMMIT;

SELECT * FROM DEPARTAMENTO;
SELECT * FROM EMPLEADO;

SELECT * FROM USUARIOS_ADMIN WHERE CORREO = 'admin@correo.cl'AND PASS = '123';

SELECT * FROM departamento, empleado;

SELECT MAX(NUMDEPTO)+1 FROM DEPARTAMENTO;

DROP TABLE USUARIOS_ADMIN;
DROP TABLE EMPLEADO;
DROP TABLE DEPARTAMENTO;

DROP SEQUENCE USUARIO_SEC;
DROP SEQUENCE DEPTO_SEC;
DROP SEQUENCE EMPL_SEC;